python main.py --datasets cora --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.0001 --dropout 0.3 --use_tntood   
python main.py --datasets cora --shift_type label --ood_class_to_leave_out 0 1 2 --num_layers 3 --learning_rate 0.001 --dropout 0.5 --use_tntood 
python main.py --datasets cora --shift_type label --ood_class_to_leave_out 1 3 4 --num_layers 2 --learning_rate 0.001 --dropout 0.5 --use_tntood --contrast_w 0.01
python main.py --datasets cora --shift_type label --ood_class_to_leave_out 2 5 6 --num_layers 3 --learning_rate 0.001 --dropout 0.0 --use_tntood --contrast_w 0.1

python main.py --datasets citeseer --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.0001 --dropout 0.5 --use_tntood --contrast_w 0.4 
python main.py --datasets citeseer --shift_type label --ood_class_to_leave_out 1 3 5 --num_layers 2 --learning_rate 0.001 --dropout 0.2 --use_tntood --contrast_w 0.05 
python main.py --datasets citeseer --shift_type label --ood_class_to_leave_out 2 3 4 --num_layers 2 --learning_rate 0.001 --dropout 0.2 --use_tntood --contrast_w 0.01 --hidden_channels 128 --tnt_loss_temp 0.01 
python main.py --datasets citeseer --shift_type label --ood_class_to_leave_out 0 1 5 --num_layers 2 --learning_rate 0.001 --dropout 0.2 --use_tntood --contrast_w 0.01 --hidden_channels 128 --tnt_loss_temp 0.01 

python main.py --datasets pubmed --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.0001 --dropout 0.5 --use_tntood --contrast_w 0.8
python main.py --datasets dblp --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.2 --use_tntood --contrast_w 0.0001 --hidden_channels 256
python main.py --datasets reddit --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.0001 --dropout 0.0 --use_tntood --contrast_w 0.4 

python main.py --datasets wikics --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.0001 --dropout 0.5 --use_tntood --contrast_w 0.001 
python main.py --datasets wikics --shift_type label --ood_class_to_leave_out 1 3 4 5 8 --num_layers 2 --learning_rate 0.0001 --dropout 0.5 --use_tntood --contrast_w 0.0001 
python main.py --datasets wikics --shift_type label --ood_class_to_leave_out 0 1 8 9 --num_layers 2 --learning_rate 0.0001 --dropout 0.5 --use_tntood --contrast_w 0.0001 
python main.py --datasets wikics --shift_type label --ood_class_to_leave_out 2 3 4 6 --num_layers 2 --learning_rate 0.001 --dropout 0.5 --use_tntood --contrast_w 0.1 

python main.py --datasets arxiv --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 --K 3
python main.py --datasets arxiv --shift_type arxiv_time --arxiv_time_bound_train 2015 2017 --arxiv_time_bound_test 2017 2018 2019 2020 --arxiv_inductive --num_layers 2 --learning_rate 0.001 --dropout 0.6 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 --contrast_w 0.9 --align_w 0.8

python main.py --datasets bookhis --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.2 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50  --tnt_loss_temp 0.1
python main.py --datasets bookhis --shift_type label --ood_class_to_leave_out 0 1 3 4 7 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets bookhis --shift_type label --ood_class_to_leave_out 1 2 6 10 11 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets bookhis --shift_type label --ood_class_to_leave_out 0 3 5 8 9 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 

python main.py --datasets bookchild --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets bookchild --shift_type label --ood_class_to_leave_out 0 2 5 9 10 11 15 18 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets bookchild --shift_type label --ood_class_to_leave_out 1 3 4 6 12 19 21 23 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets bookchild --shift_type label --ood_class_to_leave_out 0 2 5 7 8 9 10 22 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 

python main.py --datasets elephoto --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets elephoto --shift_type label --ood_class_to_leave_out 1 3 5 7 9 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets elephoto --shift_type label --ood_class_to_leave_out 0 4 6 10 11 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets elephoto --shift_type label --ood_class_to_leave_out 2 5 9 3 1 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 

python main.py --datasets elecomp --shift_type feature structure text text_swap semantic_connection --semantic_selection_mode threshold threshold threshold --target_density_factor 1 1 1 --threshold_percentile 0.75 0.85 0.95 --swap_scope both intra inter --swap_ratio 1 1 1 --text_augmentation_type synonym antonym --text_noise_level 1 1 --noise_level 0.5 0.7 0.9 --p_ii_factor 0.7 0.6 0.4 --p_ij_factor 0.5 0.3 0.7 --structure_noise_level 0.2 0.5 1.0 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50  --tnt_loss_temp 0.1
python main.py --datasets elecomp --shift_type label --ood_class_to_leave_out 1 2 3 4 5 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets elecomp --shift_type label --ood_class_to_leave_out 2 3 4 8 9 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 
python main.py --datasets elecomp --shift_type label --ood_class_to_leave_out 0 1 6 7 5 --num_layers 2 --learning_rate 0.001 --dropout 0.3 --hidden_channels 128 --use_tntood --use_batch_contrastive --early_stopping_patience 50 